# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

MIRYOKU_KANATA_OS=MAC
MIRYOKU_CLIPBOARD=MAC
MIRYOKU_ALPHAS=COLEMAK
MIRYOKU_EXTRA=QWERTY
MIRYOKU_TAP=COLEMAK
MIRYOKU_MAPPING=NOREVERSEANGLE
