name: 'Build MacOS'
on:
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
      alphas: '["colemak"]'
      clipboard: '["mac"]'
      mapping: '["custom"]'
      kmonad_os: '["mac"]'
